### ISSUE TITLE
Template don't compile with CRLF line endings ie. Windows

### ISSUE THREAD

**Issue by sztosz** [slime-lang/slime#107]
When you have template like this

```
doctype html
html
  head
    title Hello Rumbl!
  body
   Hello
```

With standard CRLF windows endings you get:

```
== Compilation error on file web/views/layout_view.ex ==
** (FunctionClauseError) no function clause matching in Slime.Doctype.for/1
    lib/slime/doctype.ex:6: Slime.Doctype.for("html\r")
    lib/slime/parser.ex:200: Slime.Parser.parse_line/2
    lib/slime/parser.ex:75: Slime.Parser.parse_line/1
    lib/slime/parser.ex:47: Slime.Parser.parse_lines/2
    lib/slime/renderer.ex:20: Slime.Renderer.precompile/1
    lib/phoenix_slime/engine.ex:9: PhoenixSlime.Engine.compile/2
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:186: Phoenix.Template."-MACRO-__before_compile__/2-fun-0-"/3
```

And I don't think this being phoenix app is relevant.

When you change line endings to standard Linux ones: LF, the compilation on the same machine does not give you any error and it simply works.

**Comment by tmbb** [comment]
Slime doesn't strip windows line endings anymore. This issue should be reopened
